[install]
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200

[test]
preload = ["./test-utils/happydom.ts", "./test-utils/testingLibrary.ts"]
root = "./src"
coverageThreshold = 0.1
