name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  check:
    runs-on: ubuntu-latest
    # container:
    #   image: mcr.microsoft.com/playwright:v1.49.0-noble
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint check
        run: bun run lint
      - name: Format check
        run: bun run fmt.check
      # - name: Unit & Integration tests
      #   run: bun run test -- --coverage
      - name: Build
        run: bun run build
      # - name: Smoke & Acceptance tests
      #   run: |
      #     bun build-storybook --quiet
      #     bunx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
      #       "bunx http-server storybook-static --port 6006 --silent" \
      #       "bunx wait-on tcp:127.0.0.1:6006 && bun test-storybook"
