name: Smoke test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: gwennlbh/playwright-bun:v1.61.1@sha256:bf82604ec8484f4188b8efe3976eeea7eed8637edb678323abe1c165738a55a5
      options: --user 1001
    steps:
      - name: Git Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Bun setup
        uses: ./.github/actions/setup

      - name: Smoke & Acceptance tests
        run: bunx vitest run --project storybook
        env:
          FORCE_COLOR: "1"
